version: 0.0
os: linux

files:
  - source: application-code/app-tier
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
  - location: scripts/before_install_app.sh
    timeout: 40
    runas: ec2-user

  AfterInstall:
    - location: scripts/after_install_app.sh
      timeout: 40
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_app.sh
      timeout: 40
      runas: ec2-user

  ApplicationStop:
    - location: scripts/stop_app.sh
      timeout: 40
      runas: ec2-user
