version: 0.2

phases:
  pre_build:
    commands:
      - echo 🔧 Installing Docker if not present...
      - yum install -y docker
      - service docker start
      - echo 🔐 Logging into Amazon ECR...
      - ACCOUNT_ID=029197504624
      - REGION=us-east-1
      - REPO_NAME=aws-three-tier-webapp
      - IMAGE_TAG=latest
      - ECR_URI=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/$REPO_NAME
      - aws --version
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com

  build:
    commands:
      - echo 🛠️ Building Docker image...
      - docker build -t $REPO_NAME .
      - docker tag $REPO_NAME:$IMAGE_TAG $ECR_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo 📤 Pushing Docker image to Amazon ECR...
      - docker push $ECR_URI:$IMAGE_TAG
      - echo ✅ Docker build and push to ECR completed.

artifacts:
  files:
    - appspec.yml
    - scripts/*
