version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Nothing to install for static site"
  pre_build:
    commands:
      - echo "Pre-build phase: cleaning old builds"
      - rm -rf build || true
      - mkdir build
  build:
    commands:
      - echo "Build phase: copying files"
      - cp -r * build/
  post_build:
    commands:
      - echo "Post-build phase: zipping artifact"
      - cd build
      - zip -r ../artifact.zip .
artifacts:
  files:
    - artifact.zip
  discard-paths: yes
