version: 0.2

phases:
  install:
    commands:
      - echo Installing backend dependencies...
      - cd application-code/app-tier
      - npm install
      - cd ../../
      - echo Installing frontend dependencies...
      - cd application-code/web-tier
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Preparing deployment artifacts...

artifacts:
  files:
    - appspec.yml
    - scripts/**  # 👈 This line is important
    - application-code/app-tier/**
    - application-code/web-tier/build/**
