version: 0.2

phases:
  install:
    commands:
      - echo Installing backend...
      - cd application-code/app-tier
      - npm install
      - cd ../../web-tier
      - echo Installing frontend...
      - npm install
  build:
    commands:
      - echo Building frontend...
      - npm run build
  post_build:
    commands:
      - echo Build phase completed.

artifacts:
  files:
    - '**/*'
